import { storefrontMedia, type PublicHomepageDto } from "@thread/types";

export const fallbackHomepage: PublicHomepageDto = {
  version: 1,
  updatedAt: "2026-07-26T00:00:00.000Z",
  sections: [
    {
      id: "announcement",
      type: "announcement",
      enabled: true,
      sortOrder: 10,
      title: "Explore the latest THREAD styles.",
      collectionSlugs: [],
      items: [],
      needsClientReview: false,
    },
    {
      id: "hero",
      type: "hero",
      enabled: true,
      sortOrder: 20,
      eyebrow: "THREAD / KOLKATA",
      title: "Style, cut from your everyday.",
      subtitle: "Explore THREAD styles for men and women.",
      primaryCta: { label: "Shop men", href: "/men" },
      secondaryCta: { label: "Shop women", href: "/women" },
      desktopImage: storefrontMedia.heroDesktop,
      mobileImage: storefrontMedia.heroMobile,
      collectionSlugs: [],
      items: [],
      needsClientReview: false,
    },
    {
      id: "audience-cards",
      type: "audience_cards",
      enabled: true,
      sortOrder: 30,
      eyebrow: "Start here",
      title: "Find your THREAD",
      collectionSlugs: [],
      items: [
        {
          id: "men",
          title: "MEN",
          subtitle: "Explore men's styles",
          href: "/men",
          image: storefrontMedia.menAudience,
        },
        {
          id: "women",
          title: "WOMEN",
          subtitle: "Explore women's styles",
          href: "/women",
          image: storefrontMedia.womenAudience,
        },
      ],
      needsClientReview: false,
    },
    {
      id: "new-arrivals",
      type: "new_arrivals",
      enabled: true,
      sortOrder: 40,
      eyebrow: "Just in",
      title: "New Arrivals",
      subtitle: "Fresh styles, newly added.",
      primaryCta: { label: "View all", href: "/search?sort=newest" },
      collectionSlugs: [],
      items: [
        {
          id: "new-men-oversized",
          title: "Men's Oversized Edit",
          subtitle: "Relaxed silhouettes with statement graphics.",
          href: "/category/oversized-t-shirts",
          image: storefrontMedia.oversizedCategory,
        },
        {
          id: "new-men-regular",
          title: "Men's Everyday Tees",
          subtitle: "Regular-fit styles for everyday rotation.",
          href: "/men",
          image: storefrontMedia.tshirtsCategory,
        },
        {
          id: "new-women-regular",
          title: "Women's Graphic Edit",
          subtitle: "Fresh regular-fit artwork and colour.",
          href: "/women",
          image: storefrontMedia.womenAudience,
        },
        {
          id: "new-all-tshirts",
          title: "The T-Shirt Line-up",
          subtitle: "Browse the latest published THREAD T-shirts.",
          href: "/category/t-shirts",
          image: storefrontMedia.regularCategory,
        },
      ],
      needsClientReview: false,
    },
    {
      id: "best-sellers",
      type: "best_sellers",
      enabled: true,
      sortOrder: 50,
      eyebrow: "Most loved",
      title: "Best Sellers",
      subtitle: "Customer favourites from THREAD.",
      primaryCta: { label: "View all", href: "/search?bestSellers=true" },
      collectionSlugs: [],
      items: [
        {
          id: "best-men",
          title: "Men's Graphic T-Shirts",
          subtitle: "A hand-picked preview from the men's catalogue.",
          href: "/men",
          image: storefrontMedia.menAudience,
        },
        {
          id: "best-women",
          title: "Women's Graphic T-Shirts",
          subtitle: "A hand-picked preview from the women's catalogue.",
          href: "/women",
          image: storefrontMedia.womenAudience,
        },
        {
          id: "best-oversized",
          title: "Oversized Fits",
          subtitle: "Explore relaxed cuts across current styles.",
          href: "/category/oversized-t-shirts",
          image: storefrontMedia.oversizedCategory,
        },
        {
          id: "best-regular",
          title: "Regular Fits",
          subtitle: "Explore classic everyday silhouettes.",
          href: "/category/t-shirts?fit=Regular",
          image: storefrontMedia.regularCategory,
        },
      ],
      needsClientReview: true,
    },
    {
      id: "categories",
      type: "categories",
      enabled: true,
      sortOrder: 60,
      eyebrow: "Explore",
      title: "Shop by Category",
      collectionSlugs: [],
      items: [
        {
          id: "t-shirts",
          title: "T-Shirts",
          href: "/category/t-shirts",
          image: storefrontMedia.tshirtsCategory,
        },
        {
          id: "oversized",
          title: "Oversized T-Shirts",
          href: "/category/oversized-t-shirts",
          image: storefrontMedia.oversizedCategory,
        },
        {
          id: "regular",
          title: "Regular Fit",
          href: "/category/t-shirts?fit=Regular",
          image: storefrontMedia.regularCategory,
        },
      ],
      needsClientReview: false,
    },
    {
      id: "collections",
      type: "collections",
      enabled: true,
      sortOrder: 70,
      eyebrow: "Curated edits",
      title: "Signature Collections",
      subtitle: "Three ways into the current THREAD catalogue.",
      collectionSlugs: [],
      items: [
        {
          id: "collection-oversized",
          title: "The Oversized Edit",
          subtitle: "Relaxed proportions, bold graphics.",
          href: "/category/oversized-t-shirts",
          image: storefrontMedia.oversizedCategory,
        },
        {
          id: "collection-everyday",
          title: "Everyday Regular",
          subtitle: "Easy silhouettes built for repeat wear.",
          href: "/category/t-shirts?fit=Regular",
          image: storefrontMedia.regularCategory,
        },
        {
          id: "collection-women",
          title: "Women's Graphic Edit",
          subtitle: "Current artwork across regular-fit styles.",
          href: "/women",
          image: storefrontMedia.womenAudience,
        },
      ],
      needsClientReview: false,
    },
    {
      id: "offer",
      type: "offer",
      enabled: true,
      sortOrder: 80,
      eyebrow: "The latest edit",
      title: "Fresh fits, ready to explore.",
      subtitle: "Discover the newest published styles in the THREAD catalogue.",
      primaryCta: { label: "View New Arrivals", href: "/search?sort=newest" },
      collectionSlugs: [],
      items: [],
      needsClientReview: false,
    },
    {
      id: "editorial",
      type: "editorial",
      enabled: true,
      sortOrder: 90,
      eyebrow: "The THREAD edit",
      title: "Everyday silhouettes. Your expression.",
      body: "Explore fits and prints across the current THREAD catalogue.",
      primaryCta: { label: "Explore T-Shirts", href: "/category/t-shirts" },
      desktopImage: storefrontMedia.editorial,
      collectionSlugs: [],
      items: [],
      needsClientReview: false,
    },
    {
      id: "brand-values",
      type: "brand_values",
      enabled: true,
      sortOrder: 100,
      eyebrow: "Our point of view",
      title: "Designed for everyday comfort.",
      body: "Explore fits made for your rotation.",
      collectionSlugs: [],
      items: [],
      needsClientReview: true,
    },
    {
      id: "trust-features",
      type: "trust_features",
      enabled: true,
      sortOrder: 110,
      eyebrow: "Shop with clarity",
      title: "Support at every step",
      collectionSlugs: [],
      items: [
        {
          id: "payments",
          title: "Secure payments",
          subtitle: "Choose from the payment methods available at checkout.",
          icon: "card",
        },
        {
          id: "support",
          title: "Customer support",
          subtitle: "Reply target within 24 hours, Monday–Friday.",
          icon: "headphones",
        },
        {
          id: "delivery",
          title: "Domestic delivery",
          subtitle: "Normally 3–7 business days.",
          icon: "truck",
        },
        {
          id: "returns",
          title: "Returns & exchanges",
          subtitle: "Eligible unworn and unwashed items within seven days of delivery.",
          icon: "refresh",
        },
      ],
      needsClientReview: true,
    },
    {
      id: "newsletter",
      type: "newsletter",
      enabled: true,
      sortOrder: 120,
      eyebrow: "Stay in the loop",
      title: "Notes from THREAD",
      subtitle: "Request product and campaign updates by email.",
      collectionSlugs: [],
      items: [],
      needsClientReview: false,
    },
    {
      id: "social",
      type: "social",
      enabled: true,
      sortOrder: 130,
      eyebrow: "THREAD social",
      title: "Follow the story",
      subtitle: "Explore releases, find your fit, or speak with the THREAD team.",
      collectionSlugs: [],
      items: [
        {
          id: "story-new",
          title: "New releases",
          subtitle: "See the newest published styles.",
          href: "/search?sort=newest",
          image: storefrontMedia.editorial,
        },
        {
          id: "story-size",
          title: "Find your fit",
          subtitle: "Review the THREAD size guide before ordering.",
          href: "/size-guide",
          image: storefrontMedia.tshirtsCategory,
        },
        {
          id: "story-contact",
          title: "Talk to THREAD",
          subtitle: "Questions about a style or order? Contact the support team.",
          href: "/contact",
          image: storefrontMedia.heroMobile,
        },
      ],
      needsClientReview: false,
    },
  ],
};
